### ISSUE TITLE
Desutorage moved to cuckchan.org

### ISSUE THREAD

**Issue by Schule04** [MayhemYDG/archives.json#41]
Desustorage.org was terminated by the registar.
Admin statement:
https://cuckchan.org/desu/thread/1250/

**Comment by MayhemYDG** [comment]
That's already been taken care of. https://github.com/MayhemYDG/archives.json/commit/7d350faaf5cf9bfa24658d047d1272052fa92781
I forgot to restart a process on my server following an https certificate renewal so that's why the json at this [url](https://mayhemydg.github.io/archives.json/archives.json) didn't get updated, sorry.
